/*

 SIMPLEBUBBLEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\dalto\Documents\GameboyDevelopment\gbtiledesigner\BubbleWall.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define SimpleBubbleMapDataWidth 40
#define SimpleBubbleMapDataHeight 18
#define SimpleBubbleMapDataBank 0

extern unsigned char SimpleBubbleMapData[];

/* End of SIMPLEBUBBLEMAP.H */
